[unstable]
build-std = ["std", "panic_abort"]

[build]
target = "wasm32-unknown-unknown"
rustc-wrapper = "sccache"
rustflags = ["-Ctarget-feature=+simd128,+atomics,+bulk-memory -Clink-arg=--shared-memory -Clink-arg=--max-memory=4294967296 -Clink-arg=--import-memory -Clink-arg=--export=__wasm_init_tls -Clink-arg=--export=__tls_size -Clink-arg=--export=__tls_align -Clink-arg=--export=__tls_base"]
